version: '3.7'

services:
  app:
    container_name: nodejs-api-app
    restart: always
    build: .
    environment:
      DB_CONNECTION: postgres://foyez:testpass@postgres:5432/nodejs-api-db
    ports:
      - '5000:5000'
    links:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: foyez
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: nodejs-api-db
      POSTGRES_HOST: postgres
    ports:
      - '5432:5432'
