version: "3.7"

services:
  app:
    container_name: nodejs-boilerplate
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
