version: '3.7'

services:
  # API
  app:
    container_name: nodejs-api-app
    restart: always
    build: .
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      REDIS_URI: redis://redis:6379
    ports:
      - '5000:5000'
    links:
      - postgres
      - redis

  # POSTGRES
  postgres:
    # container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-foyez}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-nodejs-api-db}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    ports:
      - '5432:5432'

  # REDIS
  redis:
    image: redis
    ports:
      - '6379:6379'
