POST http://localhost:5000/api/v1/signup
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "testpass"
}

###

GET http://localhost:5000/api/v1/test/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTU5NDY2MTI5NiwiZXhwIjoxNTk0NjYxNTk2fQ.WYKCYTTvgEguAj9tuYZzxqltMjI4l1IVTzK_TfwiXUA