POST http://localhost:5000/api/v1/signup
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "testpass"
}

###

GET http://localhost:5000/api/v1/test/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZW1haWwuY29tIiwiaWF0IjoxNTk0NjUwNDI0LCJleHAiOjE1OTQ2NTA3MjR9.pmXRPDW2OLyhPYYZXMSn3IhCWFZ7K6a4WPJJ8e06ilg